//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortingAlgorithmsLibTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IntegerData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntegerData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SortingAlgorithmsLibTests.IntegerData", typeof(IntegerData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///1
        ///3
        ///4
        ///5
        ///6
        ///6
        ///8
        ///8
        ///9
        ///10
        ///12
        ///14
        ///15
        ///15
        ///15
        ///16
        ///17
        ///20
        ///21
        ///22
        ///22
        ///23
        ///23
        ///23
        ///28
        ///29
        ///30
        ///31
        ///35
        ///36
        ///37
        ///39
        ///39
        ///40
        ///40
        ///41
        ///41
        ///42
        ///43
        ///43
        ///43
        ///44
        ///45
        ///45
        ///48
        ///48
        ///50
        ///50
        ///51
        ///52
        ///57
        ///58
        ///58
        ///59
        ///60
        ///60
        ///63
        ///64
        ///67
        ///68
        ///68
        ///71
        ///72
        ///75
        ///75
        ///77
        ///78
        ///79
        ///79
        ///84
        ///84
        ///84
        ///84
        ///86
        ///88
        ///89
        ///90
        ///91
        ///92
        ///93
        ///93
        ///94
        ///94
        ///95
        ///96
        ///99
        ///99
        ///99
        ///100
        ///100
        ///100
        ///101
        ///101
        ///102
        ///103
        ///104
        ///106
        ///106
        ///107
        ///108
        ///110
        ///110
        ///111
        ///112
        ///112
        ///114
        ///115
        ///115
        ///117
        ///117
        ///119
        ///119
        ///119
        ///123
        ///125
        ///127
        ///127
        ///127
        ///128
        ///130
        ///130
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SortedInteger {
            get {
                return ResourceManager.GetString("SortedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66026
        ///45889
        ///51399
        ///21033
        ///82164
        ///48695
        ///50095
        ///42459
        ///1059
        ///78275
        ///85207
        ///87970
        ///63079
        ///37818
        ///15421
        ///19452
        ///39042
        ///9255
        ///70071
        ///62945
        ///27982
        ///43876
        ///71210
        ///4136
        ///57220
        ///75983
        ///91169
        ///39175
        ///14991
        ///50428
        ///34904
        ///28170
        ///41863
        ///12545
        ///19038
        ///721
        ///2798
        ///62023
        ///15144
        ///61131
        ///33775
        ///41872
        ///91773
        ///70087
        ///42157
        ///45974
        ///90824
        ///62993
        ///16154
        ///48389
        ///43176
        ///59541
        ///63882
        ///37405
        ///2558
        ///5248
        ///27723
        ///7641
        ///59267
        ///93022
        ///92487
        ///4199
        ///88687
        ///78563
        ///77586
        ///86231
        ///75700
        ///39738
        ///4876
        ///85638
        ///73801
        ///76193
        ///52769
        ///34567
        ///24739 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedInteger {
            get {
                return ResourceManager.GetString("UnsortedInteger", resourceCulture);
            }
        }
    }
}
